---
- hosts: www

  vars:
    - root_dir: ..

  vars_files:
    - common_vars.yml

  pre_tasks:
    - debug: msg="Pre tasks section"


  tasks:
    - debug: msg="Tasks section"

    - include: "{{root_dir}}/components/project_appuser_create.yml"

    - include: "{{root_dir}}/components/project_deploy_app.yml"

    - include: "{{root_dir}}/components/project_virtualenv_create.yml"

    - include: "{{root_dir}}/components/project_tools_create.yml"

    - include: "{{root_dir}}/components/project_syncdb.yml"

    - include: "{{root_dir}}/components/project_collect_static.yml"

    - include: "{{root_dir}}/components/create_uwsgi_vassal.yml"

    - include: "{{root_dir}}/components/create_nginx_conf_uwsgi.yml"
